export const Cuidadores = [
  {
    documento: 1041691353,
    nombre: "MARIA ROMERO",
    usuario: "mromero",
    foro: "LOMA",
  },
  {
    documento: 72435983,
    nombre: "JHON CARRILLO",
    usuario: "jcarrillo",
    foro: "LOMA",
  },
  {
    documento: 1143166082,
    nombre: "ERIKA OROZCO",
    usuario: "eorozco",
    foro: "LOMA",
  },
  {
    documento: 1043165759,
    nombre: "JOSÉ PACHECO",
    usuario: "jpacheco",
    foro: "LOMA",
  },
  {
    documento: 1043149704,
    nombre: "ISABEL DE LA HOZ",
    usuario: "idelahoz",
    foro: "LOMA",
  },
  {
    documento: 72339558,
    nombre: "FERNANDO IBAÑEZ",
    usuario: "fibanez",
    foro: "LOMA",
  },
  {
    documento: 1043116135,
    nombre: "SEBASTIÁN ESCORCIA",
    usuario: "sescorcia",
    foro: "LOMA",
  },
  {
    documento: 1043116134,
    nombre: "JUAN ESCORCIA",
    usuario: "jescorcia",
    foro: "LOMA",
  },
  {
    documento: 1044210287,
    nombre: "MARIA ROMERO",
    usuario: "maromero",
    foro: "LOMA",
  },
  {
    documento: 1101455028,
    nombre: "MARCEL BANQUEZ",
    usuario: "mbanquez",
    foro: "LA SIERRITA",
  },
  {
    documento: 1045666017,
    nombre: "MARÍA GUZMÁN",
    usuario: "mguzman",
    foro: "LA SIERRITA",
  },
  {
    documento: 1140821154,
    nombre: "MARTHA SOTO",
    usuario: "msoto",
    foro: "LA SIERRITA",
  },
  {
    documento: 32882210,
    nombre: "MAYERLIN CAMPOS",
    usuario: "mcampos",
    foro: "LA SIERRITA",
  },
  {
    documento: 22732434,
    nombre: "JANELLY ATENCIO",
    usuario: "jatencio",
    foro: "LA SIERRITA",
  },
  {
    documento: 91259479,
    nombre: "ELISEO GALVIS",
    usuario: "egalvis",
    foro: "LA SIERRITA",
  },
  {
    documento: 1048220084,
    nombre: "ELÍAS BARRAZA",
    usuario: "ebarraza",
    foro: "LA SIERRITA",
  },
  {
    documento: 72161057,
    nombre: "EDUARDO MARTÍNEZ",
    usuario: "emartinez",
    foro: "LA SIERRITA",
  },
  {
    documento: 32832848,
    nombre: "REYMUNDA REVENTOS",
    usuario: "rreventos",
    foro: "LA SIERRITA",
  },
  {
    documento: 33285817,
    nombre: "LUZ VARGAS",
    usuario: "lvargas",
    foro: "LA SIERRITA",
  },
  {
    documento: 8787373,
    nombre: "ALÍ CERVANTES",
    usuario: "acervantes",
    foro: "LA SIERRITA",
  },
  {
    documento: 32732379,
    nombre: "RUBY PANTOJA",
    usuario: "rpantoja",
    foro: "LA SIERRITA",
  },
  {
    documento: 92260861,
    nombre: "PABLO CRUZ",
    usuario: "pcruz",
    foro: "MALAMBO",
  },
  {
    documento: 32610459,
    nombre: "DISNEY BAQUERO",
    usuario: "dbaquero",
    foro: "MALAMBO",
  },
  {
    documento: 1140831749,
    nombre: "KELLYS ROMERO",
    usuario: "kromero",
    foro: "MALAMBO",
  },
  {
    documento: 72049914,
    nombre: "ROYTMA ARAUJO",
    usuario: "raraujo",
    foro: "MALAMBO",
  },
  {
    documento: 1048291907,
    nombre: "ANYELY GONZÁLEZ",
    usuario: "agonzalez",
    foro: "MALAMBO",
  },
  {
    documento: 1004213477,
    nombre: "KEVIN BOLAÑO",
    usuario: "kbolano",
    foro: "SABANAGRANDE",
  },
  {
    documento: 1047361054,
    nombre: "MELANY BUSTOS",
    usuario: "mbustos",
    foro: "SABANAGRANDE",
  },
  {
    documento: 1001878455,
    nombre: "PAOLA TORRES",
    usuario: "ptorres",
    foro: "SABANAGRANDE",
  },
  {
    documento: 92522989,
    nombre: "MANUEL ANAYA",
    usuario: "manaya",
    foro: "SABANAGRANDE",
  },
  {
    documento: 19640764,
    nombre: "ALEX GALINDO",
    usuario: "agalindo",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 1234094644,
    nombre: "ANDRES VITAL",
    usuario: "avital",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 1001885555,
    nombre: "BRILLYT SAMPAYO",
    usuario: "bsampayo",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 1129509076,
    nombre: "DEYCEIBIS ROCHA",
    usuario: "drocha",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 64719449,
    nombre: "DIANA CAMARGO",
    usuario: "dcamargo",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 1140900234,
    nombre: "GINA ESCORCIA",
    usuario: "gescorcia",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 1143464461,
    nombre: "HAROLD CONDE",
    usuario: "hconde",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 1045736978,
    nombre: "JAIME SOTO",
    usuario: "jsoto",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 1143147162,
    nombre: "JAINER FIGUEROA",
    usuario: "jfigueroa",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 1070816295,
    nombre: "LUIS NAVARRO",
    usuario: "lnavarro",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 1143468548,
    nombre: "MANUEL OBREGON",
    usuario: "mobregon",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 73111909,
    nombre: "MIGUEL VITAL",
    usuario: "mvital",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 1143156926,
    nombre: "OSCAR RUIZ",
    usuario: "oruiz",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 1193575479,
    nombre: "SAYDALUZ ROJAS",
    usuario: "srojas",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 1044607804,
    nombre: "ZHARICK OBREGON",
    usuario: "zobregon",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 1048069187,
    nombre: "ALEJANDRA QUINTERO",
    usuario: "aquintero",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 1047228149,
    nombre: "CAROLINA RAMIREZ",
    usuario: "cramirez",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 1234891113,
    nombre: "DANIEL DE LA HOZ",
    usuario: "dadel",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 1143439687,
    nombre: "JESUS PARADA",
    usuario: "jparada",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 73210930,
    nombre: "JORGE BONEU",
    usuario: "jboneu",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 1045728764,
    nombre: "MARIA ARDILA",
    usuario: "mardila",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 1192747076,
    nombre: "MARIA RADA",
    usuario: "mrada",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 1140839632,
    nombre: "OMAR VARGAS",
    usuario: "ovargas",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 51942650,
    nombre: "SANDRA ROMERO",
    usuario: "sromero",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 22728490,
    nombre: "VIVIAN GUERRERO",
    usuario: "vguerrero",
    foro: "VILLA ESTADIO",
  },
  {
    documento: 8788226,
    nombre: "JOHAN SANTIAGO",
    usuario: "jsantiago",
    foro: "LAS NIEVES",
  },
  {
    documento: 1079940710,
    nombre: "JOSE GAMARRA",
    usuario: "jgamarra",
    foro: "LAS NIEVES",
  },
  {
    documento: 1001946413,
    nombre: "MIGUEL ARIZA",
    usuario: "mariza",
    foro: "LAS NIEVES",
  },
  {
    documento: 1193118858,
    nombre: "MOISES MARTINEZ",
    usuario: "mmartinez",
    foro: "LOMA",
  },
];
